{% set name = "s1etad" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c16834a6f74eb20337c7c7b354289c3b2f0a7ed2b3ca844859f2276224237b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - s1etad-cli = s1etad.cli.main:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - lxml
    - netCDF4
    - pandas
    - shapely
    - pymap3d
    - simplekml
    - gdal
    - matplotlib-base
    - argcomplete

test:
  imports:
    - s1etad
    - s1etad.cli
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/s1tools/s1-etad
  summary: 'Reader for Sentinel-1 Extended Timing Annotation Dataset'
  description: |
    The s1etad Python package provides tools for easy access to
    Sentinel-1 Extended Timing Annotation Datasets.

    The current version of the package is based on the Product Format
    Specification Document (ETAD-DLR-PS-0014) Issue 1.1.

    Main features provided are:

    * open and navigate all the S1-ETAD elements:

      - product (Sentinel1Etad class)
      - swaths (Sentinel1EtadSwath class)
      - bursts (Sentinel1EtadBurst class)

    * inspect metadata
    * perform queries on bursts (by time, swath name, product name or any
      combination) using the Sentinel1Etad.burst_catalogue
    * easy iteration
    * read corrections
    * perform correction mosaic: de-bursting and swath stitching (a basic
      algorithm is currently implemented)
    * get footprints
    * generate simple KML files of the product
    * integration with Jupyter_ environments
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://s1etad.readthedocs.io/
  dev_url: https://github.com/s1tools/s1-etad

extra:
  recipe-maintainers:
    - avalentino
